/*
--Tables :
ATHLETE
COMPOSITION_EQUIPE
DISCIPLINE
EQUIPE
EVENEMENT
HOTE
NOC
PARTICIPATION_INDIVIDUELLE
PARTICIPATION_EQUIPE
SPORT

--Vues :

MEDAILLES_ATHLETES
MedailleAth --nécessaire pour MEDAILLES_ATHLETES

MedaillesNocIntermediaire --nécessaire pour MEDAILLES_NOC
MEDAILLES_NOC

--Fonctions/procedures :

biographie(id_athlete) --ne modifie rien
resultats(id_evenement) --ne modifie rien

ajouter_resultat_individuel(id_evenement, id_athlete, code_noc, resultat) --modifie !
ajouter_resultat_equipe(id_evenement, id_equipe, resultat) --modifie !
*/

--Analyse JO:
    --Tables
GRANT SELECT ON ATHLETE TO AnalyseJO;
GRANT SELECT ON COMPOSITION_EQUIPE TO AnalyseJO;
GRANT SELECT ON DISCIPLINE TO AnalyseJO;
GRANT SELECT ON EQUIPE TO AnalyseJO;
GRANT SELECT ON EVENEMENT TO AnalyseJO;
GRANT SELECT ON HOTE TO AnalyseJO;
GRANT SELECT ON NOC TO AnalyseJO;
GRANT SELECT ON PARTICIPATION_INDIVIDUELLE TO AnalyseJO;
GRANT SELECT ON PARTICIPATION_EQUIPE TO AnalyseJO;
GRANT SELECT ON SPORT TO AnalyseJO;

    --Vues
GRANT SELECT  ON MEDAILLES_ATHLETES TO AnalyseJO;
GRANT SELECT  ON MedailleAth TO AnalyseJO;
GRANT SELECT  ON MedaillesNocIntermediaire TO AnalyseJO;
GRANT SELECT  ON MEDAILLES_NOC TO AnalyseJO;
    --Fonctions
GRANT EXECUTE ON biographie TO AnalyseJO;
GRANT EXECUTE ON resultats TO AnalyseJO;



---Gestion JO

--Tables :
GRANT SELECT, UPDATE, INSERT, DELETE ON ATHLETE TO GestionJO;
GRANT SELECT, UPDATE, INSERT, DELETE ON COMPOSITION_EQUIPE TO GestionJO;
GRANT SELECT, UPDATE, INSERT, DELETE ON DISCIPLINE TO GestionJO;
GRANT SELECT, UPDATE, INSERT, DELETE ON EQUIPE TO GestionJO;
GRANT SELECT, UPDATE, INSERT, DELETE ON EVENEMENT TO GestionJO;
GRANT SELECT, UPDATE, INSERT, DELETE ON HOTE TO GestionJO;
GRANT SELECT, UPDATE, INSERT, DELETE ON NOC TO GestionJO;
GRANT SELECT, UPDATE, INSERT, DELETE ON PARTICIPATION_INDIVIDUELLE TO GestionJO;
GRANT SELECT, UPDATE, INSERT, DELETE ON PARTICIPATION_EQUIPE TO GestionJO;
GRANT SELECT, UPDATE, INSERT, DELETE ON SPORT TO GestionJO;

GRANT SELECT ON LOG TO GESTIONJO;
--Vues :

GRANT SELECT, UPDATE, INSERT, DELETE ON MEDAILLES_ATHLETES TO GestionJO;
 --nécessaire pour MEDAILLES_ATHLETES
GRANT SELECT, UPDATE, INSERT, DELETE ON MedailleAth TO GestionJO;

 --nécessaire pour MEDAILLES_NOC
GRANT SELECT, UPDATE, INSERT, DELETE ON MedaillesNocIntermediaire TO GestionJO;
GRANT SELECT, UPDATE, INSERT, DELETE ON MEDAILLES_NOC TO GestionJO;

--Fonctions/procedures :

 --ne modifie rien
GRANT EXECUTE ON biographie TO GestionJO;
 --ne modifie rien
GRANT EXECUTE ON resultats TO GestionJO;

 --modifie !
GRANT EXECUTE ON ajouter_resultat_individuel TO GestionJO;
 --modifie !
GRANT EXECUTE ON ajouter_resultat_equipe TO GestionJO;


GRANT INSERT, SELECT, UPDATE, DELETE ON LOG TO BELHAC1;